services:
  - type: web
    name: n8n
    env: image
    plan: free
    image:
      url: n8nio/n8n:latest

    # اعتبر الخدمة جاهزة فقط لما /rest/health ترجع 200
    healthCheckPath: /rest/health

    envVars:
      # Render يمرّر الترافيك على هذا المنفذ؛ نخلي n8n يسمع عليه
      - key: PORT
        value: "10000"

      # تأكد أن واجهة الويب غير معطّلة
      - key: N8N_DISABLE_UI
        value: "false"
