services:
  - type: web
    name: n8n
    env: image
    plan: free
    image:
      url: n8nio/n8n:latest

    # ينتظر حتى تكون الخدمة جاهزة
    healthCheckPath: /rest/health

    envVars:
      - key: N8N_HOST
        value: n8n-z3ie.onrender.com
      - key: N8N_PROTOCOL
        value: https

      # مهم: خلّي التطبيق يسمع على منفذ Render
      - key: PORT
        value: 10000
      # اترك N8N_PORT غير مذكور (خليه ياخذ PORT تلقائياً)

      # خفّف التعقيد: لا تضع EDITOR_BASE_URL مؤقتاً
      - key: N8N_WEBHOOK_URL
        value: https://n8n-z3ie.onrender.com/

      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # مؤقتاً عطّل Basic Auth لتسهيل التشخيص
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
