services:
  - type: web
    name: n8n
    env: image
    plan: free
    image:
      url: n8nio/n8n:latest

    # خليه ما يوجّه الترافيك إلا بعد ما يكون n8n جاهز
    healthCheckPath: /rest/health

    envVars:
      # Render يمرر الترافيك إلى PORT، خلّي n8n يسمع على نفس المنفذ
      - key: PORT
        value: 10000
      - key: N8N_PORT
        value: 10000

      - key: N8N_HOST
        value: n8n-z3ie.onrender.com
      - key: N8N_PROTOCOL
        value: https

      # مهم وجودها للروابط الداخلية والويبهوكس
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-z3ie.onrender.com/
      - key: N8N_WEBHOOK_URL
        value: https://n8n-z3ie.onrender.com/

      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # خلال التشخيص خلّيها "false" لتجنّب حجب healthcheck
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
