services:
  - type: web
    name: n8n
    env: image
    plan: free
    image:
      url: n8nio/n8n:latest

    healthCheckPath: /rest/health

    envVars:
      # Render يرسل الترافيك للكونتينر على هذا المنفذ
      - key: PORT
        value: "10000"

      # ثبّت مسار الواجهة على الجذر صراحة
      - key: N8N_PATH
        value: "/"

      # لا تعطّل الواجهة بأي حال
      - key: N8N_DISABLE_UI
        value: "false"

      # (اختياري لكن مفيد لاحقًا)
      - key: DB_SQLITE_POOL_SIZE
        value: "2"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: GENERIC_TIMEZONE
        value: "UTC"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
